version: 0.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: 3ao0xfd0XGfGS2+NFuBYgOZiTkM3lZbZ5yLwk9OaEkqC3tkkBGREsgmBJLSwwBDc
before_build:
  - nuget restore SwagAttack_Gameserver_Mirror\GameServer\GameServer.sln
  - nuget restore SwagAttack_GUI_Webserver_Mirror\GUI\GUI.sln
build_script:
  - dotnet build SwagAttack_Gameserver_Mirror\GameServer\GameServer.sln
  - dotnet build SwagAttack_GUI_Webserver_Mirror\GUI\GUI.sln
after_test:
  - cmd: after_test.cmd