job: 
  include: 
  	- stage: "test"
  	language: csharp
  	solution: SwagAttack_Gameserver_Mirror/GameServer/GameServer.sln
  	mono: latest
  	dotnet: 2.0.0
  	script:
  	 - dotnet restore
  	install:
  	  - nuget restore SwagAttack_Gameserver_Mirror/GameServer/GameServer.sln
  	  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  	script:
  	  - dotnet build SwagAttack_Gameserver_Mirror/GameServer/GameServer.sln