language: csharp
mono: latest
dotnet: 2.0.0
script:
- dotnet restore
install:
- nuget restore SwagAttack_Gameserver_Mirror/GameServer/GameServer.sln
- nuget restore SwagAttack_GUI_Webserver_Mirror/GUI/GUI.sln
- nuget install NUnit.Runners -Version 3.10.1.0 -OutputDirectory testrunner
script:
- dotnet build SwagAttack_Gameserver_Mirror/GameServer/GameServer.sln
- dotnet build SwagAttack_GUI_Webserver_Mirror/GUI/GUI.sln
- mono ./testrunner/NUnit.Runners.3.10.1.0/tools/nunit-console.exe ./**/**/*.Test.*/bin/Debug/netcoreapp2.0/*tests.dll
